### ISSUE TITLE
Metadata doesn't meet the following requirements:

### ISSUE THREAD

**Issue by mikepaxton** [ballerburg9005/wget-2-zim#10]
I'm new to using wget-2-zim so forgive me if I'm missing something obvious here.  I'm not sure why I'm continually getting this message at the tail end of the process?  I'm getting the same error for every website I've tried.

Wget finished.
iterating over .html files to fix links, css and stuff
find: ‘meshtastic.org/wget-2-zim-overreach/’: No such file or directory
mv: cannot stat 'meshtastic.org/wget-2-zim-overreach/*': No such file or directory
iteration finished
deleting files deemed too large
deleting files finished
writing ZIM
Metadata doesn't meet the following requirements:
    Name must contain at least 1 characters
FAILURE! Left meshtastic.org download directory in place.

**Comment by ballerburg9005** [comment]
This seems to be an error generated by a change in the zim tools. I try to fix it.

**Comment by ballerburg9005** [comment]
Works now, thanks for reporting the issue.

**Comment by mikepaxton** [comment]
> Works now, thanks for reporting the issue.

Thanks so much for fixing the issue so fast.  Just pulled the latest version and ran it, worked great!
