### ISSUE TITLE
Is there a way to not download files like PDF?

### ISSUE THREAD

**Issue by nicosims** [ballerburg9005/wget-2-zim#11]
As I'm using this tool, I see that most of the time is spent downloading pdfs and other files I don't really care about, I just want the website text. Is it possible to prevent it from downloading all that?

**Comment by ballerburg9005** [comment]
Yes, simply add the stuff you want to exclude to the variable WGETREJECT inside the script.

It has no cmd switch for pdfs by default, because documents are very small and usually very relevant to the content.
