### ISSUE TITLE
zimwriterfs error due to --illustration option 

### ISSUE THREAD

**Issue by jjschwarz** [ballerburg9005/wget-2-zim#2]
zimwriterfs on Debian 11 seems to no longer support the --illustration option and has changed it to --favicon instead.  I have done a quick replacement on my local copy of the file and that seems to resolve the issue

**Comment by ballerburg9005** [comment]
Please use the latest Git version, which does not suffer from this problem.

The Debian packages are probably severely outdated (years).

In extremely old zim-tools, it is not only this option that has been renamed. This is why I will not address such old versions.
