### ISSUE TITLE
Image hotlinking detection triggered

### ISSUE THREAD

**Issue by sindastra** [ballerburg9005/wget-2-zim#4]
For some reason, `wget-2-zim.sh` triggers [Cloudflare's image hotlink detection](https://developers.cloudflare.com/support/more-dashboard-apps/cloudflare-scrape-shield/understanding-cloudflare-hotlink-protection/).

According to the above linked documenation:

> Hotlink Protection will deny access to requests when the HTTP referer does not include your website domain name (and is not blank).

I looked at `wget-2-zim.sh` and I am currently testing a fix. If it works, I'll open a PR.

**Comment by sindastra** [comment]
I have successfully tested a fix and submitted a PR.

**Comment by ballerburg9005** [comment]
Ok thanks. But weird, the way it was before should have done the exact same thing.
