### ISSUE TITLE
`wget: unrecognized option '--referer:'`

### ISSUE THREAD

**Issue by ilyaigpetrov** [ballerburg9005/wget-2-zim#6]
https://github.com/ballerburg9005/wget-2-zim/blob/6f83e1125fe3cc09be4e2f1bc2c1fdc42959cc66/wget-2-zim.sh#L140

`--header="X-Requested-With: XMLHttpRequest" --referer: "$DOMAIN" \`

This line throws:
```sh-session
DEBUG: <SOME URL> ( requested by: SOME MORE )
wget: unrecognized option '--referer:'                                                                                                                                  
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
```

I guess, `--referer:` should be `--referer=`.

**Comment by ballerburg9005** [comment]
Fixed. Thanks.
