### ISSUE TITLE
Error: `ls: Argument list too long`

### ISSUE THREAD

**Issue by ilyaigpetrov** [ballerburg9005/wget-2-zim#8]
`WELCOME="$(command ls -w 1 $DOMAIN/index*.{htm*,php*} $DOMAIN/*.{htm*,php*} | cat - <(echo "$DOMAIN/index.html") | head -n 1 | sed "s#^[^/]*/##g")"`:

https://github.com/ballerburg9005/wget-2-zim/blob/6f83e1125fe3cc09be4e2f1bc2c1fdc42959cc66/wget-2-zim.sh#L280

`line 280: /usr/bin/ls: Argument list too long`

**Comment by ballerburg9005** [comment]
Fixed.
